### ISSUE TITLE
--proxy doesn't work with SOCKS5 proxy

### ISSUE THREAD

**Issue by yegor256** [yegor256/rumble#13]
I'm trying to send an email via Gmail SMTP and can't do that. The authentication doesn't go through. I reported to the gem we are using, but no response so far: https://github.com/camertron/net-smtp-proxy/issues/2 Also asked in SO: https://stackoverflow.com/questions/55287305/cant-send-smtp-via-socks-proxy-authentication-required

The list of SOCKS5 proxies can be found, for example, here: http://free-proxy.cz/en/proxylist/country/all/socks5/ping/all

Tried with a bounty: https://www.bountysource.com/issues/71936008-proxy-doesn-t-work-with-socks5-proxy

**Comment by kazcw** [comment]
It looks like that library is for HTTP proxies. Square peg, round hole. You will need to either use an HTTP proxy, or use a library that is for SOCKS proxies.

**Comment by yegor256** [comment]
@kazcw do you think it's possible to send SMTP via a HTTP proxy?

**Comment by kazcw** [comment]
@yegor256 That's [what camertron/net-smtp-proxy is](https://github.com/camertron/net-smtp-proxy#what-is-this-thing):

> What is this Thing?

> This gem allows you to connect to an SMTP server by way of an HTTP proxy. Why would you want to do that? I'm sure a number of use-cases exist, but I specifically needed to connect to the Gmail SMTP relay service in order to send an email from a company-wide alias. Normally, Gmail requires you to provide the credentials for the sender's account when sending an email. The relay service however replaces the usual password authentication with IP whitelisting. You provide Google with a static IP address that all your SMTP requests will come from. The SMTP relay service also allows you to send email from company-wide email aliases, i.e. accounts that don't have a login. In our case, we wanted to send an email from the Platform Engineering Team as opposed to one specific member of that team. We already had Squid set up as a reverse proxy with a static IP, so we whitelisted the IP with Google and wrote this gem to send SMTP requests through the proxy.

**Comment by yegor256** [comment]
@kazcw it seems that `camertron/net-smtp-proxy` is using [ruby-proxifier](https://github.com/samuelkadolph/ruby-proxifier) for proxifying, which supports both HTTP and SOCKS proxies.

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.2`

**Comment by 0crat** [comment]
Job `gh:yegor256/rumble#13` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
